### ISSUE TITLE
Shot Manager 2.x roadmap

### ISSUE THREAD

**Issue by werwack** [ubisoft/shotmanager#27]
Here are the features and topic that I plan to address in the next releases of Shot Manager.
The order and priority of the tasks may change. Please comment if you have specific needs.

**V 2.0:**
- [x] #28
- [x] Improvement of the UX of the Interactive Shots Stack
- [x] Better support of storyboard materials
- [x] Teaser and some feature videos for storyboarding

**V 2.1:**
- [ ] Lock of the storyboard frames to the start time of shots, associated support in Retimer
- [ ] Support of Blender 3.3 VSE features dedicated to storyboarding
- [ ] Json file for Project settings
- [ ] Progress bar for batch rendering

**V 2.2:**
- [ ] Tools to paint on free grease pencil objects, support of 2.5D storyboarding
